language: python

python: 2.7

env:
    - TOXENV=cov
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33

branches:
    only:
        - master
        - develop

install: pip install --quiet --use-mirrors tox

script: tox

after_script:
    - if [ $TOXENV == "cov" ]; then
        pip install --quiet --use-mirrors coveralls;
        coveralls;
      fi
